/*
 * 2 botones (Color y forma) dentro de ellos sus respectivas cosas (Hecho)
 * Tamaño completo adecuado (Hecho)
 * Boton Jorge 
 * Arreglar guardar figuras(Hecho)
 * Seleccionado de las formas arreglar
 */
package codigo;

import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.Component;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.JFileChooser;
import javax.swing.JMenu;
import javax.swing.JToggleButton;

/**
 *
 * @author Marco Girbau
 */
public class VentanaPaint extends javax.swing.JFrame {

    BufferedImage buffer, buffer2 = null;
    Forma miForma;
    
    Color colorSeleccionado = Color.BLACK;
    int formaSeleccionada = 3;  //Si vale 100 pinto circulos
                                //Si vale 1 pinto cuadrados
                                //Si vale 3 pinto triangulos
                                //Si vale 5 pinto pentagonos 
                                //Si vale 2 pinto linea
                                //Si vale 6 pinto hexagono
                                //Si vale 8 pinto octogono
                                //Si vale 24 pinta estrellas normales
                                //Si vale 12 pinta segundo tipo de estrellas
    Graphics2D bufferGraphics, buffer2Graphics, jPanelGraphics = null;
    BasicStroke trazo1 = new BasicStroke(15);
    BasicStroke trazo2 = new BasicStroke(15,
                                        BasicStroke.CAP_BUTT,
                                        BasicStroke.JOIN_MITER, 
                                        10.0f, 
                                        new float[]{10.0f}, 
                                        0.0f);
    /**
     * Creates new form VentanaPaint
     */
    public VentanaPaint() {
        initComponents();
        jLabel1.setBackground(Color.ORANGE);
        inicializaBuffers();
        jDialog1.setSize(720, 480);
        jDialog3.setSize(320, 300);
    }

    private void inicializaBuffers()
    {
        //creo una imagen del mismo ancho que alto en el lienzo
        buffer = (BufferedImage)jPanel1.createImage(jPanel1.getWidth(), jPanel1.getHeight());
        //creo una imagen modificable
        bufferGraphics = buffer.createGraphics(); 
        //inicializa el buffer para que sean un rectangulo rojo que ocupe todo el jpanel
        bufferGraphics.setColor(Color.white);
        bufferGraphics.fillRect(0, 0, buffer.getWidth(), buffer.getHeight());
        
        //inicializo el 2º buffer
        buffer2 = (BufferedImage)jPanel1.createImage(jPanel1.getWidth(), jPanel1.getHeight());
        //creo una imagen modificable
        buffer2Graphics = buffer2.createGraphics(); 
        //inicializa el buffer para que sean un rectangulo rojo que ocupe todo el jpanel
        buffer2Graphics.setColor(Color.white);
        buffer2Graphics.fillRect(0, 0, buffer2.getWidth(), buffer2.getHeight());
        
        jPanelGraphics = (Graphics2D)jPanel1.getGraphics();
    }
    
    @Override
    public void paint(Graphics g)
    {
        super.paint(g);
        //pinto el buffer sobre el jFrame
        jPanelGraphics.drawImage(buffer, 0, 0, null);
    }
    
    public void deSelecciona()
     {
        Component[] components = (Component[]) getContentPane().getComponents();
        for (Component comp : components) {
            if (comp instanceof JToggleButton) {
                ((JToggleButton)comp).setSelected(false);
            }
        } 
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jColorChooser1 = new javax.swing.JColorChooser();
        CancelBoton1 = new javax.swing.JButton();
        SaveBoton1 = new javax.swing.JButton();
        GrosorSlider = new javax.swing.JSlider();
        jDialog2 = new javax.swing.JDialog();
        jFileChooser1 = new javax.swing.JFileChooser();
        jDialog3 = new javax.swing.JDialog();
        CancelBoton2 = new javax.swing.JButton();
        SaveBoton2 = new javax.swing.JButton();
        CuadradoBoton = new javax.swing.JToggleButton();
        CirculoBoton = new javax.swing.JToggleButton();
        LineaBoton = new javax.swing.JToggleButton();
        TrianguloBoton = new javax.swing.JToggleButton();
        PentagonoBoton = new javax.swing.JToggleButton();
        Estrella1 = new javax.swing.JToggleButton();
        Hexagono = new javax.swing.JToggleButton();
        Octogono = new javax.swing.JToggleButton();
        Estrella2 = new javax.swing.JToggleButton();
        RellenoCheckBox = new javax.swing.JCheckBox();
        RellenoCheckBox1 = new javax.swing.JCheckBox();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        JorgePincel = new javax.swing.JToggleButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        jDialog1.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                jDialog1ComponentAdded(evt);
            }
        });

        jColorChooser1.setColor(new java.awt.Color(0, 0, 0));

        CancelBoton1.setText("Cancelar");
        CancelBoton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                CancelBoton1MousePressed(evt);
            }
        });

        SaveBoton1.setText("Guardar");
        SaveBoton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                SaveBoton1MousePressed(evt);
            }
        });
        SaveBoton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveBoton1ActionPerformed(evt);
            }
        });

        GrosorSlider.setOrientation(javax.swing.JSlider.VERTICAL);
        GrosorSlider.setValue(5);
        GrosorSlider.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                GrosorSliderMouseDragged(evt);
            }
        });

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jColorChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, 635, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(GrosorSlider, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialog1Layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(CancelBoton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(SaveBoton1)
                .addGap(161, 161, 161))
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(GrosorSlider, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(52, 52, 52))
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jColorChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CancelBoton1)
                    .addComponent(SaveBoton1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jFileChooser1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFileChooser1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDialog2Layout = new javax.swing.GroupLayout(jDialog2.getContentPane());
        jDialog2.getContentPane().setLayout(jDialog2Layout);
        jDialog2Layout.setHorizontalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jFileChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 636, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jDialog2Layout.setVerticalGroup(
            jDialog2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialog2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jFileChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        CancelBoton2.setText("Cancelar");
        CancelBoton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                CancelBoton2MousePressed(evt);
            }
        });
        CancelBoton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelBoton2ActionPerformed(evt);
            }
        });

        SaveBoton2.setText("Guardar");
        SaveBoton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                SaveBoton2MousePressed(evt);
            }
        });
        SaveBoton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveBoton2ActionPerformed(evt);
            }
        });

        CuadradoBoton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/cuadrado.png"))); // NOI18N
        CuadradoBoton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                CuadradoBotonMousePressed(evt);
            }
        });

        CirculoBoton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/circulo.png"))); // NOI18N
        CirculoBoton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                CirculoBotonMousePressed(evt);
            }
        });

        LineaBoton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/linea.png"))); // NOI18N
        LineaBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LineaBotonActionPerformed(evt);
            }
        });

        TrianguloBoton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/triangulo.png"))); // NOI18N
        TrianguloBoton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                TrianguloBotonMousePressed(evt);
            }
        });

        PentagonoBoton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/pentagono.png"))); // NOI18N
        PentagonoBoton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                PentagonoBotonMousePressed(evt);
            }
        });

        Estrella1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/estrella1.png"))); // NOI18N
        Estrella1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Estrella1MousePressed(evt);
            }
        });

        Hexagono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/hexagono.png"))); // NOI18N
        Hexagono.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                HexagonoMousePressed(evt);
            }
        });
        Hexagono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HexagonoActionPerformed(evt);
            }
        });

        Octogono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/octagono.png"))); // NOI18N
        Octogono.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                OctogonoMousePressed(evt);
            }
        });
        Octogono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OctogonoActionPerformed(evt);
            }
        });

        Estrella2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/estrella2.png"))); // NOI18N
        Estrella2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Estrella2MousePressed(evt);
            }
        });
        Estrella2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Estrella2ActionPerformed(evt);
            }
        });

        RellenoCheckBox.setText("Relleno");
        RellenoCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RellenoCheckBoxActionPerformed(evt);
            }
        });

        RellenoCheckBox1.setText("Rayado");
        RellenoCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RellenoCheckBox1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDialog3Layout = new javax.swing.GroupLayout(jDialog3.getContentPane());
        jDialog3.getContentPane().setLayout(jDialog3Layout);
        jDialog3Layout.setHorizontalGroup(
            jDialog3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDialog3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CuadradoBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CirculoBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PentagonoBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jDialog3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(RellenoCheckBox1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(RellenoCheckBox, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jDialog3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDialog3Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(SaveBoton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(CancelBoton2))
                    .addGroup(jDialog3Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(jDialog3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialog3Layout.createSequentialGroup()
                                .addComponent(TrianguloBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                                .addComponent(Hexagono, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jDialog3Layout.createSequentialGroup()
                                .addComponent(LineaBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Octogono, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jDialog3Layout.createSequentialGroup()
                                .addComponent(Estrella1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Estrella2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jDialog3Layout.setVerticalGroup(
            jDialog3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDialog3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDialog3Layout.createSequentialGroup()
                        .addComponent(CuadradoBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(CirculoBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(PentagonoBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(RellenoCheckBox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                        .addComponent(RellenoCheckBox1)
                        .addContainerGap())
                    .addGroup(jDialog3Layout.createSequentialGroup()
                        .addGroup(jDialog3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TrianguloBoton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Hexagono, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jDialog3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Octogono, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LineaBoton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jDialog3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Estrella1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Estrella2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jDialog3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SaveBoton2)
                            .addComponent(CancelBoton2)))))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setForeground(new java.awt.Color(255, 255, 255));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jPanel1MouseReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 709, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 485, Short.MAX_VALUE)
        );

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/colores.png"))); // NOI18N
        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel1MousePressed(evt);
            }
        });

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/formaschachis.png"))); // NOI18N
        jLabel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel2MousePressed(evt);
            }
        });

        JorgePincel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/JorgeCisnerospincel.jpg"))); // NOI18N
        JorgePincel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                JorgePincelMousePressed(evt);
            }
        });
        JorgePincel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JorgePincelActionPerformed(evt);
            }
        });

        jMenu1.setText("File");
        jMenu1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jMenu1StateChanged(evt);
            }
        });

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Guardatu");
        jMenuItem1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuItem1MousePressed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setText("Cargar");
        jMenuItem2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenuItem2MousePressed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JorgePincel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(JorgePincel, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
        
        bufferGraphics.drawImage(buffer2, 0, 0,null);
        if(RellenoCheckBox1.isSelected())
        {
            trazo1 = new BasicStroke(GrosorSlider.getValue(),BasicStroke.CAP_BUTT,BasicStroke.JOIN_MITER,10.0f,  new float[]{10.0f},0.0f);
        }
        else
        {
           //trazo1 = new BasicStroke(GrosorSlider.getValue(),BasicStroke.CAP_BUTT,BasicStroke.JOIN_MITER,10.0f,  new float[]{10.0f},0.0f); 
        }
        miForma.dibujate(bufferGraphics, evt.getY(),evt.getX(),trazo1);
        repaint(0,0,1,1);
    }//GEN-LAST:event_jPanel1MouseDragged

    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
        // inicializa la forma que usare para dibujar en el buffer
        switch(formaSeleccionada)
        {
            case 100: miForma = new Circulo(evt.getX(), evt.getY(), colorSeleccionado, RellenoCheckBox.isSelected());
            break;
            case 1: miForma = new Cuadrado(evt.getX(), evt.getY(), colorSeleccionado, RellenoCheckBox.isSelected());
            break;
            case 3: miForma = new Triangulo(evt.getX(), evt.getY(), colorSeleccionado, RellenoCheckBox.isSelected());
            break;
            case 5: miForma = new Pentagono(evt.getX(), evt.getY(), colorSeleccionado, RellenoCheckBox.isSelected());
            break;
            case 24: miForma = new Estrella(evt.getX(), evt.getY(), colorSeleccionado, RellenoCheckBox.isSelected());
            break;
            case 2: miForma = new Linea(evt.getX(), evt.getY(), colorSeleccionado, RellenoCheckBox.isSelected());
            break;
            case 6: miForma = new Hexagono(evt.getX(), evt.getY(), colorSeleccionado, RellenoCheckBox.isSelected());
            break;
            case 8: miForma = new Octogono(evt.getX(), evt.getY(), colorSeleccionado, RellenoCheckBox.isSelected());
            break;
            case 12: miForma = new Estrella2(evt.getX(), evt.getY(), colorSeleccionado, RellenoCheckBox.isSelected());
            break;
        }
    }//GEN-LAST:event_jPanel1MousePressed

    private void jPanel1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseReleased
        //dibuja la forma correspondiente
      if(RellenoCheckBox1.isSelected())
        {
            trazo1 = new BasicStroke(GrosorSlider.getValue(),BasicStroke.CAP_BUTT,BasicStroke.JOIN_MITER,10.0f,  new float[]{10.0f},0.0f);
        }
        else
        {
           //trazo1 = new BasicStroke(GrosorSlider.getValue(),BasicStroke.CAP_BUTT,BasicStroke.JOIN_MITER,10.0f,  new float[]{10.0f},0.0f); 
        }
       miForma.dibujate(buffer2Graphics, evt.getY(),evt.getX(), trazo1);
    }//GEN-LAST:event_jPanel1MouseReleased

    private void jLabel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MousePressed
        jDialog1.setVisible(true);
    }//GEN-LAST:event_jLabel1MousePressed

    private void CancelBoton1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CancelBoton1MousePressed
        jDialog1.setVisible(false);
    }//GEN-LAST:event_CancelBoton1MousePressed

    private void SaveBoton1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SaveBoton1MousePressed
        jDialog1.setVisible(false);
        colorSeleccionado = jColorChooser1.getColor();
        jLabel1.setBackground(colorSeleccionado);
    }//GEN-LAST:event_SaveBoton1MousePressed

    private void CirculoBotonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CirculoBotonMousePressed
        //Elige circulos chachis paraguays
        formaSeleccionada = 100;
        deSelecciona();
    }//GEN-LAST:event_CirculoBotonMousePressed

    private void CuadradoBotonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CuadradoBotonMousePressed
        //Elige cuadrados chachis paraguays
        formaSeleccionada = 1;
        deSelecciona();
    }//GEN-LAST:event_CuadradoBotonMousePressed

    private void TrianguloBotonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TrianguloBotonMousePressed
        formaSeleccionada = 3;
        deSelecciona();
    }//GEN-LAST:event_TrianguloBotonMousePressed

    private void PentagonoBotonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PentagonoBotonMousePressed
        formaSeleccionada = 5;
        deSelecciona();
    }//GEN-LAST:event_PentagonoBotonMousePressed

    private void Estrella1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Estrella1MousePressed
        formaSeleccionada = 24;
        deSelecciona();
    }//GEN-LAST:event_Estrella1MousePressed

    private void jMenuItem1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem1MousePressed
        int seleccion = jFileChooser1.showSaveDialog(this);
        if(seleccion == JFileChooser.APPROVE_OPTION)
        {
            //Si llego aqui es que el usuario ha pulsado en "Guardar" cuando ha salido en el menu de jFileChooser
            File fichero = jFileChooser1.getSelectedFile();
            String nombre = fichero.getName();
            String extension = nombre.substring(nombre.lastIndexOf('.') + 1);
            if(extension.equalsIgnoreCase("jpg") || extension.equalsIgnoreCase("png"))
            {
                try
                {
                    ImageIO.write(buffer, extension, fichero);
                }
                catch(IOException e)
                {
                    
                }
            }
        }
    }//GEN-LAST:event_jMenuItem1MousePressed

    private void jMenu1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jMenu1StateChanged
        JMenu menu = (JMenu) evt.getSource();
        if(!menu.isSelected())
        {
            repaint();
        }
    }//GEN-LAST:event_jMenu1StateChanged

    private void jFileChooser1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFileChooser1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFileChooser1ActionPerformed

    private void jMenuItem2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem2MousePressed
        int seleccion = jFileChooser1.showOpenDialog(this);
        
        if (seleccion == JFileChooser.APPROVE_OPTION)
        {
            //si llego aquí es que el usuario ha pulsado en "guardar" cuando ha salido 
            //el menú del jFileChooser
            File fichero = jFileChooser1.getSelectedFile();
            String nombre = fichero.getName();
            String extension = nombre.substring(nombre.lastIndexOf('.')+1);
            BufferedImage imagen = null;
            if (extension.equalsIgnoreCase("jpg") || extension.equalsIgnoreCase("png"))
            {
                try
                {
                    imagen = ImageIO.read(fichero);
                    bufferGraphics.drawImage(imagen, 0, 0, null);
                    buffer2Graphics.drawImage(imagen, 0, 0, null);
                    repaint();
                }
                catch(IOException e)
                {
                    
                }
            }
        }
    }//GEN-LAST:event_jMenuItem2MousePressed

    private void CancelBoton2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CancelBoton2MousePressed
        jDialog3.setVisible(false);
    }//GEN-LAST:event_CancelBoton2MousePressed

    private void SaveBoton2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SaveBoton2MousePressed
        jDialog3.setVisible(false);
    }//GEN-LAST:event_SaveBoton2MousePressed

    private void SaveBoton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveBoton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SaveBoton1ActionPerformed

    private void HexagonoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HexagonoMousePressed
        deSelecciona();
    }//GEN-LAST:event_HexagonoMousePressed

    private void OctogonoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OctogonoMousePressed
        deSelecciona();
    }//GEN-LAST:event_OctogonoMousePressed

    private void Estrella2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Estrella2MousePressed
        deSelecciona();
    }//GEN-LAST:event_Estrella2MousePressed

    private void jLabel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MousePressed
        jDialog3.setVisible(true);
    }//GEN-LAST:event_jLabel2MousePressed

    private void RellenoCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RellenoCheckBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RellenoCheckBoxActionPerformed

    private void GrosorSliderMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GrosorSliderMouseDragged
        // TODO add your handling code here:
    }//GEN-LAST:event_GrosorSliderMouseDragged

    private void SaveBoton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveBoton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SaveBoton2ActionPerformed

    private void CancelBoton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelBoton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CancelBoton2ActionPerformed

    private void jDialog1ComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_jDialog1ComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jDialog1ComponentAdded

    private void LineaBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LineaBotonActionPerformed
        formaSeleccionada = 2;
        deSelecciona();
    }//GEN-LAST:event_LineaBotonActionPerformed

    private void HexagonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HexagonoActionPerformed
        formaSeleccionada = 6;
        deSelecciona();
    }//GEN-LAST:event_HexagonoActionPerformed

    private void OctogonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OctogonoActionPerformed
        formaSeleccionada = 8;
        deSelecciona();
    }//GEN-LAST:event_OctogonoActionPerformed

    private void Estrella2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Estrella2ActionPerformed
        formaSeleccionada = 12;
        deSelecciona();
    }//GEN-LAST:event_Estrella2ActionPerformed

    private void JorgePincelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JorgePincelMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_JorgePincelMousePressed

    private void JorgePincelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JorgePincelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JorgePincelActionPerformed

    private void RellenoCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RellenoCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RellenoCheckBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPaint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPaint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPaint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPaint.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPaint().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CancelBoton1;
    private javax.swing.JButton CancelBoton2;
    private javax.swing.JToggleButton CirculoBoton;
    private javax.swing.JToggleButton CuadradoBoton;
    private javax.swing.JToggleButton Estrella1;
    private javax.swing.JToggleButton Estrella2;
    private javax.swing.JSlider GrosorSlider;
    private javax.swing.JToggleButton Hexagono;
    private javax.swing.JToggleButton JorgePincel;
    private javax.swing.JToggleButton LineaBoton;
    private javax.swing.JToggleButton Octogono;
    private javax.swing.JToggleButton PentagonoBoton;
    private javax.swing.JCheckBox RellenoCheckBox;
    private javax.swing.JCheckBox RellenoCheckBox1;
    private javax.swing.JButton SaveBoton1;
    private javax.swing.JButton SaveBoton2;
    private javax.swing.JToggleButton TrianguloBoton;
    private javax.swing.JColorChooser jColorChooser1;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JDialog jDialog2;
    private javax.swing.JDialog jDialog3;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
